apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cats-dogs-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: cats-dogs-app
  endpoints:
  - port: http
    path: /metrics
    interval: 15s