apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cats-dogs-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: cats-dogs-app
  endpoints:
  - port: http
    path: /metrics
    interval: 10s